Vizzuality/GCPM

app/assets/javascripts/helpers/marker_layer.js, app/sql_queries/projects_map_points.sql.erb
This Pr contains a fix to set the id of the event markers correctly
=> Map: event click redirect fixed

app/assets/javascripts/controllers/user_controller.js, app/assets/javascripts/views/map/index.js, app/assets/javascripts/views/map/layers/carto-layer.js, public/data/layersSpec.json
Fixes basemap on user profile.
=> Sets basemap depending on the section & layersSpec

app/assets/javascripts/collections/organizations_types_collection.js, app/assets/javascripts/presenters/filter_form_presenter.js, app/assets/javascripts/presenters/project_form/cancer_types_presenter.js, app/assets/javascripts/presenters/project_form/countries_presenter.js, app/assets/javascripts/presenters/project_form/organizations_presenter.js, app/assets/javascripts/presenters/project_form/organizations_types_presenter.js, app/assets/javascripts/presenters/project_form/pickadateend_presenter.js, app/assets/javascripts/presenters/project_form/pickadatenew_presenter.js, app/assets/javascripts/presenters/project_form/pickadatestart_presenter.js, app/assets/javascripts/presenters/project_form/project_types_presenter.js, app/assets/javascripts/router.js, app/assets/javascripts/templates/filter_form.hbs, app/assets/javascripts/templates/form/pickadate.hbs, app/assets/javascripts/templates/modal.hbs, app/assets/javascripts/views/filter_form_view.js, app/assets/javascripts/views/form/pickdatenew.js, app/assets/javascripts/views/form/select.js, app/assets/javascripts/views/modal_view.js, app/assets/stylesheets/_animations.scss, app/assets/stylesheets/_mixins.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button-container.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_pickadate.scss, app/assets/stylesheets/components/_select.scss, app/assets/stylesheets/components/_spinner.scss, app/assets/stylesheets/layouts/_grid.scss, app/assets/stylesheets/layouts/_project_add.scss
This PR adds:
- Pickadate component
- Modal filter styles
- Modal spinner
- Organization types select
- Little refactor of the input/field rendering
=> Datepicker & filter styles

app/assets/stylesheets/layouts/_header.scss
=> adjust header padding to design

app/assets/javascripts/collections/countries_collection.js, app/assets/javascripts/presenters/breadcrumbs_presenter.js, app/assets/javascripts/presenters/filter_form_presenter.js, app/assets/javascripts/presenters/project_form/countries_presenter.js, app/assets/javascripts/templates/breadcrumbs.hbs, app/assets/javascripts/views/modal_view.js, app/assets/stylesheets/_animations.scss, app/assets/stylesheets/_mixins.scss, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_select2-override.scss, app/assets/stylesheets/components/_spinner.scss
This PR adds:
- Breadcrumbs: Names of regions/countries instead of isos
- Filters: whenever you filter by a country, it will set the region too
=> Filters and breadcrumbs

app/assets/javascripts/presenters/share_presenter.js, app/assets/javascripts/templates/share.hbs, app/assets/javascripts/views/share_view.js, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_share-social.scss
We need to check facebook one, I don't know why it's not working
=> Share: social buttons added

app/assets/javascripts/presenters/map_presenter.js, app/assets/javascripts/templates/filter_form.hbs, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/_btn-container.scss, app/assets/stylesheets/components/_btn.scss, app/views/investigators/show.html.erb, app/views/projects/show.html.erb, app/views/shared/_user_actions.html.erb
This PR adds:
- User actions
- Little refactor of the buttons, at least easier to understand
=> User: user actions inside investigator and project page

app/controllers/countries_controller.rb
This PR changes the order of the tabs and set the data as the first option
=> Data: set country data tab at the first option

app/assets/javascripts/controllers/cancer_types_controller.js, app/assets/javascripts/controllers/countries_controller.js, app/controllers/cancer_types_controller.rb, app/controllers/countries_controller.rb, app/views/cancer_types/show.html.erb, app/views/countries/show.html.erb, app/views/investigators/show.html.erb, app/views/projects/show.html.erb, app/views/shared/_user_actions.html.erb, config/locales/en.yml
This Pr adds:
- Button added to country and cancer type page. 
- Redirect to login if user does not exist
=> Follow button 

app/assets/javascripts/presenters/filter_form_presenter.js, app/assets/javascripts/presenters/project_form/pickadateend_presenter.js, app/assets/javascripts/presenters/project_form/pickadatestart_presenter.js
This PR fixes an issue where the filter reset button would not reset the filters.
=> Filter reset button fix

app/assets/javascripts/controllers/countries_controller.js
Set `data` as default param only in the country controller
=> Bug: set data as default param only in the country controller

app/assets/javascripts/presenters/country_data_presenter.js
=> Country: sql improved

app/assets/javascripts/helpers/layers/bubble_layer.js, app/assets/javascripts/templates/infowindow.hbs, app/assets/javascripts/templates/infowindow_bubble.hbs, app/assets/stylesheets/components/_infowindow.scss, app/sql_queries/people_map_points.sql.erb, app/sql_queries/projects_map_points.sql.erb
This PR adds:
- mouseover popups for country and region bubbles
- investigator address added to marker popups
=> Infowindows

app/sql_queries/people_map_points.sql.erb, app/sql_queries/projects_map_points.sql.erb
Bug solved and organization name included in the people call too
=> Map: api bug solved

app/assets/javascripts/templates/infowindow.hbs, app/assets/stylesheets/components/_infowindow.scss, app/sql_queries/people_map_points.sql.erb, app/sql_queries/projects_map_points.sql.erb
This PR adds the organization to the infowindow of Project/points and People/points
=> Map: infowindows updated with organization

app/assets/javascripts/presenters/map_vis_presenter.js, app/controllers/events_controller.rb, app/views/users/show.js.erb
Show network when coming from another tab in user section.
Show projects and events map markers in each detail page.
=> Network shown when changing tab & projects & events detail page markers

app/assets/javascripts/helpers/layers/marker_cluster_layer.js, app/assets/javascripts/templates/infowindow.hbs, lib/assets/javascripts/PruneCluster/PruneCluster.js
This PR adds:
- Popup for clusters
=> Map: clusters popup

app/controllers/organizations_controller.rb, app/views/organizations/show.html.erb
This PR adds:
- Remove unnecessary counters. 
- Add people tab
=> Organizations: remove unnecessary counters. Add people tab

app/assets/javascripts/presenters/country_data_presenter.js, app/assets/javascripts/templates/country_data.hbs
This PR adds:
- A solution for countries that don't have data
=> Countries: deal with countries with no data

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_summary_info.scss, app/views/projects/show.html.erb
This PR adds:
- Correct number of collaborators
- Remove unnecessary hover
- Pointer events in the info related to the project
=> Project: little style fixes. Info updated

app/views/investigators/show.html.erb
=> Investigator: post tab added

app/assets/stylesheets/components/_btn-container.scss, app/controllers/investigators_controller.rb, app/views/investigators/show.html.erb
This PR removes the events tab from the investigator page and set conditionals in a better way
=> Investigator: style fixes.

app/assets/javascripts/presenters/actionbar_presenter.js, app/assets/javascripts/presenters/layers_presenter.js, app/assets/javascripts/templates/actionbar.hbs, app/controllers/map_controller.rb
This PR adds:
- "Add Project/Event" to action bar
- It will change depending on the state.data attribute
=> Map: add project/event button added to map actionbar

app/assets/javascripts/presenters/download_presenter.js, app/assets/javascripts/presenters/map_presenter.js, app/assets/javascripts/presenters/sortby_presenter.js, app/assets/javascripts/views/legend_view.js
This PR adds:
- Map bugs fixed
- Legend improvement
=> Map: bug, improvements and rock&roll

app/views/events/_list.html.erb, app/views/posts/_list.html.erb, app/views/projects/_list.html.erb
This PR adds:
- "Edit" button added to projects-events-posts inside the user profile
=> Network: edit buttons added to preject/event/post list

app/views/shared/_user_actions.html.erb
Let's see if this fixes the error
=> Follow: Remove current investigator condition for the moment

app/assets/javascripts/helpers/layers/marker_cluster_layer.js
This PR set the sizes of the bubbles. Let's see if this works
=> Map: cluster sizes

app/assets/images/icons/selection_home.json, app/assets/stylesheets/components/_claim.scss, app/assets/stylesheets/components/_icons.scss, app/views/home/index.html.erb, app/views/shared/_icons_home.html.erb
This PR adds a claim in the home with 4 buttons:
- New Project
- New Event
- New Post
- Network
Of course, if the user is not logged in, he will be redirected to the log in page.
=> Home: register claim

app/assets/javascripts/collections/widgets_collection.js
We need to be sure that the axises are present before parsing them.
=> Widgets: bug json parse fixed

app/assets/javascripts/controllers/investigators_controller.js, app/assets/javascripts/controllers/users_controller.js, app/assets/javascripts/presenters/messages_actions_presenter.js, app/assets/javascripts/views/messages_actions_view.js, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form_message.scss, app/assets/stylesheets/layouts/_grid.scss, app/controllers/users_controller.rb, app/helpers/general_helper.rb, app/views/messages/_list.html.erb, app/views/shared/_user_actions.html.erb, app/views/users/_net_list.html.erb, app/views/users/_network.html.erb, config/locales/en.yml
Show user follow and message buttons and a add them to network list.
=> User followable and network list

app/views/search/index.html.erb
=> Search results grid

app/helpers/general_helper.rb, app/views/countries/show.js.erb, app/views/events/_list.html.erb
Fix country detail page show.js when switching tabs.
=> Fix show.js on country detail & events tab

app/assets/javascripts/presenters/country_data_presenter.js, app/assets/javascripts/templates/country_data.hbs
This PR adds:
- Screening programs subdivided
=> Country: split screening programs in 3

app/assets/javascripts/presenters/events_form_presenter.js, app/assets/javascripts/presenters/map_vis_presenter.js, app/assets/javascripts/views/event_form_view.js, app/assets/javascripts/views/map_view.js.erb, app/assets/stylesheets/components/_map.scss, app/views/network_events/_form.html.erb
This Pr removes the latitude and longitude inputs and it changes them to a map. It will be easier to use and understand for the user.
=> Events: location behaviour

app/assets/javascripts/controllers/countries_controller.js, app/assets/javascripts/presenters/map_vis_presenter.js
This PR adds:
- Country: fit bounds
=> Country: fit bounds of country instead of markers

app/views/shared/_user_actions.html.erb
This is not my best code, but it works...(I think)
=> Messages: button in users and investigators without errors

app/admin/concerns/featurable.rb, app/admin/event.rb, app/admin/featured.rb, app/admin/investigator.rb, app/admin/organization.rb, app/admin/project.rb, app/controllers/home_controller.rb, app/models/concerns/act_as_featured.rb, app/models/event.rb, app/models/featured.rb, app/models/investigator.rb, app/models/organization.rb, app/models/post.rb, app/models/project.rb, app/serializers/project_serializer.rb, app/views/home/_list.html.erb, db/migrate/20161124170341_create_featureds.rb, db/structure.sql, spec/models/featured_spec.rb, spec/models/project_spec.rb
This PR adds:
- Home featureds projects/investigators/organizations/events
IMPORTANT! Log into the admin and set some featured. The weight column inside the featured list will set the priority of this featured element.
=> Home featureds

app/assets/javascripts/collections/countries_collection.js, app/assets/javascripts/presenters/filter_form_presenter.js, app/assets/javascripts/presenters/project_form/countries_presenter.js, app/assets/javascripts/presenters/project_form/regions_presenter.js, app/assets/javascripts/templates/filter_form.hbs, app/assets/javascripts/views/form/select.js
=> Regions filter

app/assets/javascripts/controllers/investigators_controller.js, app/controllers/investigators_controller.rb
Hide investigator data graph when being on mobile as its type it's not appropriate for mobile.
=> Hide investigator data graph on mobile

app/assets/javascripts/presenters/user_network_list_presenter.js
Make logic work when switching tabs on user's network.
=> Network lists work when switching tabs

app/assets/javascripts/controllers/map_controller.js, app/assets/javascripts/presenters/filter_bar_presenter.js, app/assets/javascripts/templates/filter_bar.hbs, app/assets/javascripts/views/filter_bar_view.js, app/assets/stylesheets/components/_filter-bar.scss, app/views/map/_desktop_index.html.erb
Filter bar added above the counters
=> Filter bar

app/views/investigators/_net_list.html.erb
=> Organization path by slug or id

app/admin/widget.rb, app/assets/javascripts/collections/widgets_collection.js, app/assets/javascripts/controllers/home_controller.js, app/assets/javascripts/presenters/project_form/widgets_featured_presenter.js, app/assets/stylesheets/components/_widget-featured.scss, app/controllers/home_controller.rb, app/views/home/index.html.erb, db/structure.sql
This PR adds:
- Featured widget black in the home page
- We need to add some global widgets to the home page to let them know how to use it
=> Featured widgets

app/assets/javascripts/presenters/cancer_types_data_presenter.js, app/assets/javascripts/templates/ranking.hbs, app/assets/javascripts/views/ranking.js
Info added to rankings on cancer types page
=> Ranking info

app/assets/javascripts/presenters/sortby_presenter.js, app/controllers/countries_controller.rb, app/controllers/investigators_controller.rb, app/controllers/map_controller.rb, app/controllers/organizations_controller.rb, app/controllers/users_controller.rb, app/models/event.rb, app/models/notification.rb
Events sorted by upcoming dates
=> Events upcoming
